services:
  # --- 1. TRAEFIK (Reverse Proxy ตัวกลาง) ---
  traefik:
    image: traefik:v2.11
    container_name: nan-verse-traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    environment:
      - DOCKER_API_VERSION=1.40 # 👈 บังคับเวอร์ชัน API ของ Docker Client ตรงนี้
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web-network
    restart: always

  # --- 2. BACKEND SERVER ---
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nan-verse-server
    env_file:
      - ./server/.env
    networks:
      - web-network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.pichaya.dev`)"
      - "traefik.http.services.server.loadbalancer.server.port=8000"

  # --- 3. FRONTEND CLIENT ---
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nan-verse-client
    env_file:
      - ./client/.env.local
    environment:
      - PORT=3000
      - FASTAPI_URL=http://server:8000
    networks:
      - web-network
    restart: always
    depends_on:
      - server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`nanlocalverse.pichaya.dev`)"
      - "traefik.http.services.client.loadbalancer.server.port=3000"

networks:
  web-network:
    name: nan-verse-net